import React from 'react';
import Card from '../../../core/layout/Card';
import Alert from '../../../core/layout/Alert';
import Separator from '../../../core/layout/Separator';
import SuspectUsageAlertListContainer from './SuspectUsageAlertListContainer';
import SuspectUsageAlertListFilterContainer from './SuspectUsageAlertListFilterContainer';
import SuspectUsageAlertFormDialogContainer from './SuspectUsageAlertFormDialogContainer';

const SuspectUsageAlertScene = () => (
  <div>
    <Alert title="How are alerts created?">
      <p>
        These alerts are generated by comparing the student execution with the average execution of other students.
        The students in the above list may are having some trouble to do the exercise or studying in the wrong way.
      </p>
    </Alert>
    <Separator size="xs"/>
    <Card title="Suspect Usage Alerts">
      <SuspectUsageAlertListFilterContainer />
    </Card>
    <Separator />
    <Card>
      <SuspectUsageAlertListContainer />
    </Card>
    <SuspectUsageAlertFormDialogContainer />
  </div>
);

export default SuspectUsageAlertScene;
